### ISSUE TITLE
App crashes when enabling an already enabled mod

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#38]
I downloaded a mod, enabled it and then deleted `importedMods.json`. When I reloaded the app and downloaded it again, it worked fine, clearly detecting the mod already existed in the `DownLoaded` folder. However when I clicked to enable it, the app crashed. The log file ends at `Enabling 0e3917bf-6ccd-4f93-a889-0357622ddf6c`

I assume the issue arises when the app can't copy the mod folder from `DownLoaded` for `premium_cache` as the folder/files already exists, so it crashes

**Comment by Ikethepro18** [comment]
The same effect can be replicated by changing `"IsLoaded"` to true in `importedMods.json`

**Comment by MohammedGamer85** [comment]
also your assumption is correct. as the copy funcation I use does not override the files and since i didn't expect the code to crach i didn't make a catch mythod if it crashes

**Comment by MohammedGamer85** [comment]
![image](https://github.com/MohammedGamer85/MythosApp/assets/100155245/eae1b87e-245e-4dee-97ae-408c38bc9bb8)
