### ISSUE TITLE
Importing mods doesn't import

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#65]
The only item from `modinfo.json` that actually seems to be imported properly is the version and last date/time it was updated

**Comment by MohammedGamer85** [comment]
Is that in the latest version @Ikethepro18

**Comment by MohammedGamer85** [comment]
Sorry for the late response. finally got my school Schedule in order

**Comment by Ikethepro18** [comment]
I think so but I'll double check when I get home. I think it was the 1.0 prerelease which was the same as the 1.0 release
