### ISSUE TITLE
Strange blank hover text on installed mods

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#67]
When hovering over this spot on my installed mods (and a little below), this bar appears which looks to me like hover text that just doesn't have any content. I think it's related to the mods missing certain categories on the right as the bar appears where text should appear when hovering over a mod with these categories. Also don't mind the buggy looking mod, that's just a product of me messing about
![image](https://github.com/MohammedGamer85/Mythtic/assets/73065710/debfdcc9-3df4-4c16-9fc4-af7c1e13fc65)
_Bugged mod_

![image](https://github.com/MohammedGamer85/Mythtic/assets/73065710/fed17a43-238d-4b60-bb88-edada714f49f)
_Not bugged mod_

**Comment by MohammedGamer85** [comment]
hmmmm i do not have much to work with here best guess is that mod was installed before the update. -although that shouldn't be a problem i made sure of that- so the ModCategory enums did get set up. @Ikethepro18

**Comment by MohammedGamer85** [comment]
you said you where missing about could you tell me what you did exactly?

**Comment by Ikethepro18** [comment]
> you said you where missing about could you tell me what you did exactly?

I'll be honest I don't really remember, it was back when the last version released and that mod is totally busted. The ones with the issue were from before the update as you suspected though

**Comment by MohammedGamer85** [comment]
@Ikethepro18 hay man this bug is impossible as it is a if else statement the only way it can happen is you set it to null in the files.
```cs
                    ModTypes = (BP == true && RP == true)
                    ? Enums.ModTypes.RPBP
                    : (RP == false)
                        ? Enums.ModTypes.BP
                        : Enums.ModTypes.RP,
```

**Comment by MohammedGamer85** [comment]
if you can provide a way to replicate it that would be ideal

**Comment by MohammedGamer85** [comment]
Not replicatable
