### ISSUE TITLE
Issue with importing mods

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#68]
I'll detail exactly what I did to make things easier
I exported a mod that I had installed, worked absolutely fine as far as I can tell, and then I tried to import the mod and it wouldn't let me as the mod was already installed (speaking of which you should give the user to cancel or overwrite the installed mod in that situation I think) so I deleted the installed mod and tried to import it and it said 'Failed to import mod, Exception is Object reference not set to an instance of an object.'
Log of me launching, trying to import and then closing the client is also attached below if it helps
[09-12-2023 14;10;56.txt](https://github.com/MohammedGamer85/Mythtic/files/13624350/09-12-2023.14.10.56.txt)

**Comment by MohammedGamer85** [comment]
@Ikethepro18 
i will make a form later for issues but could you please include `All the Structures.mclmod` file

**Comment by MohammedGamer85** [comment]
i need it to know if it is was exported currently.

**Comment by MohammedGamer85** [comment]
another thing how did you convert the `all the structures` mode into .mclmod

**Comment by Ikethepro18** [comment]
> another thing how did you convert the `all the structures` mode into .mclmod

Yes I did. I can only send it here as a ZIP though because GitHub doesn't let you upload .mclmod files but it's the same file, just with a different extension. I can send the original .mclmod file in Discord if that helps too? 
[All the Structures.zip](https://github.com/MohammedGamer85/Mythtic/files/13624950/All.the.Structures.zip)

Also the Log from when it was exported
[09-12-2023 13;53;11.txt](https://github.com/MohammedGamer85/Mythtic/files/13624953/09-12-2023.13.53.11.txt)

**Comment by MohammedGamer85** [comment]
> > another thing how did you convert the `all the structures` mode into .mclmod
> 
> Yes I did. I can only send it here as a ZIP though because GitHub doesn't let you upload .mclmod files but it's the same file, just with a different extension. I can send the original .mclmod file in Discord if that helps too? [All the Structures.zip](https://github.com/MohammedGamer85/Mythtic/files/13624950/All.the.Structures.zip)
> 
> Also the Log from when it was exported [09-12-2023 13;53;11.txt](https://github.com/MohammedGamer85/Mythtic/files/13624953/09-12-2023.13.53.11.txt)

perfect thanks. no need for the .mclmod file i was gonna convert it any way

**Comment by Ikethepro18** [comment]
Also want to add that I may have been using the wrong client version like in issue #69. Either way, it still doesn't import in the new version of the client, this time quoting that it is already installed

**Comment by MohammedGamer85** [comment]
Fixed in 1.1.1
