### ISSUE TITLE
Searching does not work at all

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#69]
Doesn't matter what I search for, only that weird 'Dev mod' you sent over a while ago shows
![image](https://github.com/MohammedGamer85/Mythtic/assets/73065710/fe2a0923-bcaf-48e7-9e92-ccdddf9695b3)
_All installed mods_

![image](https://github.com/MohammedGamer85/Mythtic/assets/73065710/ffe08f83-51b0-4dc9-b37d-ec736100cf68)
_What all searches will show_

**Comment by Ikethepro18** [comment]
Also nice issue number

**Comment by MohammedGamer85** [comment]
@Ikethepro18 that is the older version look 
![Animation5645172fdyhv](https://github.com/MohammedGamer85/Mythtic/assets/100155245/12ccab3a-5e46-4cb9-a0a8-fa112bc7dd97)

**Comment by Ikethepro18** [comment]
I'm not sure it was now but you should totally add the version number into settings somewhere to make it easier

Also the change from the `mythtic.Desktop.exe` file to `v1.1 Mythtic.exe` has confused me a bit. It looks all good on my end too so this can be closed
