### ISSUE TITLE
Redownloading mod caused it to break

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#70]
I tried to redownload a mod because it had no icon and when I did, the client claimed it was all good, then it said it couldn't overwrite a file and now the mod isn't listed. Log attached
[09-12-2023 16;35;46.txt](https://github.com/MohammedGamer85/Mythtic/files/13624974/09-12-2023.16.35.46.txt)

It left no files behind, totally just destructed itself and happily let me install it from the Discover tab

**Comment by MohammedGamer85** [comment]
@Ikethepro18  please delete the file and try again
![image](https://github.com/MohammedGamer85/Mythtic/assets/100155245/77818bb6-9eb6-43b1-9750-3abc57f20f3b)

![njsbnjklfasbdfbasdfbjkl](https://github.com/MohammedGamer85/Mythtic/assets/100155245/63bcad54-266a-4cd8-b843-1319071513ea)

**Comment by Ikethepro18** [comment]
It's working fine without any changes. I think there must have been an issue with the mod for whatever reason Not sure what though, I think most of my installed mods were pretty busted

**Comment by MohammedGamer85** [comment]
okay if it happens again please just @MohammedGamer85
