### ISSUE TITLE
Latest version time for mods in discover just use time of client launch

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#71]
The time of the latest version for mods in the discover page uses the time the client launched rather than the time the most recent version of the mod was released
![image](https://github.com/MohammedGamer85/Mythtic/assets/73065710/84727420-527e-40dd-8251-b81d56236f61)
_The latest version time on one launch_

![image](https://github.com/MohammedGamer85/Mythtic/assets/73065710/b3712717-38ab-4c7b-a95f-ab5c7b8f6cce)
_The latest version time on a second launch_

**Comment by Ikethepro18** [comment]
That's the date as well as the time

**Comment by MohammedGamer85** [comment]
@Ikethepro18 Sir you are in the wrong place please go report this at https://discord.com/channels/1100055308832882698/1147718731728965703
![image](https://github.com/MohammedGamer85/Mythtic/assets/100155245/02f33f2a-ce35-4ea0-8b1e-8126b269a59d)

**Comment by MohammedGamer85** [comment]
![image](https://github.com/MohammedGamer85/Mythtic/assets/100155245/18f77c5f-2729-4700-92e1-07f726604a9a)

**Comment by Ikethepro18** [comment]
Ah, I see
