### ISSUE TITLE
User icon/name doesn't load on first log in

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#73]
I know this is a very well known issue but I felt it still needed an official issue to track it. This has been like it is since forever and is fixed upon reopening the client

**Comment by MohammedGamer85** [comment]
@Ikethepro18 i know a fix idk when i will implement it.

**Comment by MohammedGamer85** [comment]
i just have to reload the profile class after the image is downloaded

**Comment by Ikethepro18** [comment]
> i just have to reload the profile class after the image is downloaded

But will that fix the username too?

**Comment by MohammedGamer85** [comment]
Yep
all the infromation is put in the right place it just does not get updated

**Comment by MohammedGamer85** [comment]
I fixed it in v1.2.1 the ago old but that existed as past me had no understanding of code order.
