### ISSUE TITLE
Auto Enable Mod on Install does not work

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#76]
As simple as it sounds, I enabled this setting and when I download mods, they're disabled. I've also tried enabling the setting and restarting the client but to no avail

**Comment by MohammedGamer85** [comment]
AHhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh. well blame me for that.

**Comment by MohammedGamer85** [comment]
as i open VS planned to add it and then forgot all it takes is a if statement.
