### ISSUE TITLE
'App is not affiliated' statement should be in settings

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#77]
I understand the importance of this statement from a legal standpoint, but I think it's quite intrusive and the client would look significantly better if it was positioned elsewhere, such as in the settings tab

**Comment by MohammedGamer85** [comment]
Agree will put it beside the version number at the bottom in small font.

**Comment by MohammedGamer85** [comment]
![image](https://github.com/MohammedGamer85/Mythtic/assets/100155245/14ef5599-612d-4452-b426-c69995fa2557)
DONE YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
