### ISSUE TITLE
Strange lines intersecting 'Mythtic' logo

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#78]
It's hard to see from a distance, but up close you can see 4 distinct lines intersecting the logo especially down the centre
![image](https://github.com/MohammedGamer85/Mythtic/assets/73065710/d1934636-54eb-48cc-836d-b090e42105c5)

Maybe this was a stylistic choice, but if it was it was a very strange one to make

**Comment by MohammedGamer85** [comment]
![image](https://github.com/MohammedGamer85/Mythtic/assets/100155245/cc099207-2671-4fc1-a1f4-9332244fd004)
noticed them but thought they where from my app. shouldn't be to hard to fix

**Comment by MohammedGamer85** [comment]
the logo does have quite a few oddities

**Comment by MohammedGamer85** [comment]
![image](https://github.com/MohammedGamer85/Mythtic/assets/100155245/6a64db3e-2118-4eea-bb8d-1c72acb80163)
@Ikethepro18 Fixed
