### ISSUE TITLE
Erroneous '.' in mod versions

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#80]
Mods seem to have an extra '.' placed at the end of their latest version when viewed on the Home page.
![image](https://github.com/MohammedGamer85/Mythtic/assets/73065710/657bd8f4-d169-484f-b699-2bfe7dc94818)
_On the home page_

![image](https://github.com/MohammedGamer85/Mythtic/assets/73065710/cd54adf6-0419-4010-9eec-851fe65ca23b)
_On the Mythos website_

This seems to be written into `importedMods.json` when the mod is downloaded for some reason and shouldn't be there both for aesthetic reasons and because it's mathematically incorrect

**Comment by MohammedGamer85** [comment]
Definitely noticed it idk what cases it tho will look into it

**Comment by MohammedGamer85** [comment]
![image](https://github.com/MohammedGamer85/Mythtic/assets/100155245/3773b6c9-6edd-4966-b6f6-7e17d370b91a)
![image](https://github.com/MohammedGamer85/Mythtic/assets/100155245/2632c9d4-f6c7-44d4-b8f4-bb0450c3209f)
i was trying to separate the different parts. well it is fixed now
