### ISSUE TITLE
Updating doesn't work

### ISSUE THREAD

**Issue by RZ302** [MohammedGamer85/Mythtic#81]
![grafik](https://github.com/MohammedGamer85/Mythtic/assets/77217875/b02a3984-6004-400c-b68f-8b24ff24254e)

Uploaded an update for my skin pack today, and this is what I get on clicking the update button.

**Comment by MohammedGamer85** [comment]
@RZ302 please send the log files they are in 
`%userprofile%\Documents\Mythtic\Logs`

Solution use the redownload button for now.

**Comment by RZ302** [comment]
Error: The directory is not empty (movePack)
Log:

[GetRequest] making request to https://mythos.legendsmodding.com/api/myth/10011
[GetRequest] made successfull request to `https://mythos.legendsmodding.com/api/myth/10011`. json:' {"success":true,"data":{"id":10011,"name":"RZ-Skin","creator":{"id":27,"username":"RZ302"},"gamemode":"Campaign","shortdescription":"My Minecraft skin in Minecraft Legends","longdescription":"[b][u]Me saying stuff:[/u][/b]\r\nMy Minecraft skin ported into Legends using Miclee's basic Minecraft hero model. If you play with this skin you automatically look up to 92% better than the average Legends player, that is scientifically proven.\r\nI used this skin for both Minecraft and Java Edition for many years now and do not remember its origins clearly. Should I have a downloaded skin as the base for this of which you are the original creator, please refrain from legal action.\r\n\r\n[b][u]Install instructions:[/u][/b]\r\n- Unpack the ZIP archive to a new folder\r\n- Move the folder to %AppData%\\AppData\\Roaming\\Minecraft Legends\\internalStorage\\premiumcache\\resourcepacks","category":{"id":1,"name":"Uncategorized"},"releasedate":null,"defaultimage":"9e7483a6f0e336e2e41c0e7002d4d120","youtubelink":"","discordlink":"KjfQw5m9US","twitterlink":"","githublink":"","images":[{"id":124,"imagehash":"9e7483a6f0e336e2e41c0e7002d4d120"},{"id":125,"imagehash":"2a26710f0370ad7dff4091313ba1204b"},{"id":126,"imagehash":"2a26710f0370ad7dff4091313ba1204b"}],"versions":[{"id":10,"version":"1.0.1","filehash":"4d67ee2d20a940a5ccd32cd8d42636eb","uploaddate":"2023-12-26T22:06:37.000Z"},{"id":9,"version":"1.0.0","filehash":"a8b03b037524c63f83638e9d91076dd7","uploaddate":"2023-12-25T01:51:08.000Z"}],"downloads":0,"approved":1}} '
[DownloadFile] downloading file from 'https://static.legendsmodding.com/myths/4d67ee2d20a940a5ccd32cd8d42636eb.zip' to 'C:\Users\Admin\Documents\Mythtic\Temp' with name `\Mod.zip`.
[DownloadFile] Download completed successfuly!

(JsonReaderHelper) 'Add' Reading: C:\Users\Admin\Documents\Mythtic\Temp\Mod\manifest.json Result: 
'mythtic.Features.Mod.Rootobject'
(movePack) Failed to moved pack[RP]. Error[Das Verzeichnis ist nicht leer. : 'C:\Users\Admin\Documents\Mythtic\DownLoaded\0d16ef64-6302-402d-8b2c-f57e6a51efc5\RP-0d16ef64-6302-402d-8b2c-f57e6a51efc5']
JsonWriterHelper Writing To: C:\Users\Admin\Documents\Mythtic\DownLoaded\0d16ef64-6302-402d-8b2c-f57e6a51efc5\modInfo.json Data: System.Func`1[System.String]

JsonWriterHelper Writing To: importedMods.json Data: System.Func`1[System.String]

Failed to update Mod:RZ-Skin. Error:[System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at mythtic.Desktop.UI.MVVM.ViewModels.ModPageViewModel.getInstalledModInfo(Int32 id) in C:\Users\moham\source\repos\Avlonia\mythosApp\mythos.Desktop\UI\MVVM\ViewModels\ModPageViewModel.cs:line 136
   at mythtic.Desktop.UI.MVVM.ViewModels.ModPageViewModel..ctor(Int32 id, Boolean Installed) in C:\Users\moham\source\repos\Avlonia\mythosApp\mythos.Desktop\UI\MVVM\ViewModels\ModPageViewModel.cs:line 115
   at mythtic.Desktop.UI.MVVM.Views.ModPage..ctor(Int32 id, Boolean Installed) in C:\Users\moham\source\repos\Avlonia\mythosApp\mythos.Desktop\UI\MVVM\Views\ModPage.axaml.cs:line 13
   at mythtic.Desktop.UI.MVVM.ViewModels.HomePageViewModel.<>c.<.ctor>b__13_2() in C:\Users\moham\source\repos\Avlonia\mythosApp\mythos.Desktop\UI\MVVM\ViewModels\HomePageViewModel.cs:line 85
   at mythtic.Features.Mod.UpdateMod.CheckForUpdates(ImportedModsItem ImportedModInfo, String feedBackMode) in C:\Users\moham\source\repos\Avlonia\mythosApp\mythos\Features\Mod\CheckForUpdates.cs:line 44]

**Comment by MohammedGamer85** [comment]
@RZ302 could you please give full log file as i would like to see the start message of the update operation

**Comment by MohammedGamer85** [comment]
> Error: The directory is not empty (movePack) Log:
> 
> ```
> [GetRequest] made successfull request to `https://mythos.legendsmodding.com/api/myth/10011`. json:' {"success":true,"data":{"id":10011,"name":"RZ-Skin","creator":{"id":27,"username":"RZ302"},"gamemode":"Campaign","shortdescription":"My Minecraft skin in Minecraft Legends","longdescription":"[b][u]Me saying stuff:[/u][/b]\r\nMy Minecraft skin ported into Legends using Miclee's basic Minecraft hero model. If you play with this skin you automatically look up to 92% better than the average Legends player, that is scientifically proven.\r\nI used this skin for both Minecraft and Java Edition for many years now and do not remember its origins clearly. Should I have a downloaded skin as the base for this of which you are the original creator, please refrain from legal action.\r\n\r\n[b][u]Install instructions:[/u][/b]\r\n- Unpack the ZIP archive to a new folder\r\n- Move the folder to %AppData%\\AppData\\Roaming\\Minecraft Legends\\internalStorage\\premiumcache\\resourcepacks","category":{"id":1,"name":"Uncategorized"},"releasedate":null,"defaultimage":"9e7483a6f0e336e2e41c0e7002d4d120","youtubelink":"","discordlink":"KjfQw5m9US","twitterlink":"","githublink":"","images":[{"id":124,"imagehash":"9e7483a6f0e336e2e41c0e7002d4d120"},{"id":125,"imagehash":"2a26710f0370ad7dff4091313ba1204b"},{"id":126,"imagehash":"2a26710f0370ad7dff4091313ba1204b"}],"versions":[{"id":10,"version":"1.0.1","filehash":"4d67ee2d20a940a5ccd32cd8d42636eb","uploaddate":"2023-12-26T22:06:37.000Z"},{"id":9,"version":"1.0.0","filehash":"a8b03b037524c63f83638e9d91076dd7","uploaddate":"2023-12-25T01:51:08.000Z"}],"downloads":0,"approved":1}} '
> [DownloadFile] downloading file from 'https://static.legendsmodding.com/myths/4d67ee2d20a940a5ccd32cd8d42636eb.zip' to 'C:\Users\Admin\Documents\Mythtic\Temp' with name `\Mod.zip`.
> [DownloadFile] Download completed successfuly!
> 
> (JsonReaderHelper) 'Add' Reading: C:\Users\Admin\Documents\Mythtic\Temp\Mod\manifest.json Result: 
> 'mythtic.Features.Mod.Rootobject'
> (movePack) Failed to moved pack[RP]. Error[Das Verzeichnis ist nicht leer. : 'C:\Users\Admin\Documents\Mythtic\DownLoaded\0d16ef64-6302-402d-8b2c-f57e6a51efc5\RP-0d16ef64-6302-402d-8b2c-f57e6a51efc5']
> JsonWriterHelper Writing To: C:\Users\Admin\Documents\Mythtic\DownLoaded\0d16ef64-6302-402d-8b2c-f57e6a51efc5\modInfo.json Data: System.Func`1[System.String]
> 
> JsonWriterHelper Writing To: importedMods.json Data: System.Func`1[System.String]
> 
> Failed to update Mod:RZ-Skin. Error:[System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
>    at System.Collections.Generic.List`1.get_Item(Int32 index)
>    at mythtic.Desktop.UI.MVVM.ViewModels.ModPageViewModel.getInstalledModInfo(Int32 id) in C:\Users\moham\source\repos\Avlonia\mythosApp\mythos.Desktop\UI\MVVM\ViewModels\ModPageViewModel.cs:line 136
>    at mythtic.Desktop.UI.MVVM.ViewModels.ModPageViewModel..ctor(Int32 id, Boolean Installed) in C:\Users\moham\source\repos\Avlonia\mythosApp\mythos.Desktop\UI\MVVM\ViewModels\ModPageViewModel.cs:line 115
>    at mythtic.Desktop.UI.MVVM.Views.ModPage..ctor(Int32 id, Boolean Installed) in C:\Users\moham\source\repos\Avlonia\mythosApp\mythos.Desktop\UI\MVVM\Views\ModPage.axaml.cs:line 13
>    at mythtic.Desktop.UI.MVVM.ViewModels.HomePageViewModel.<>c.<.ctor>b__13_2() in C:\Users\moham\source\repos\Avlonia\mythosApp\mythos.Desktop\UI\MVVM\ViewModels\HomePageViewModel.cs:line 85
>    at mythtic.Features.Mod.UpdateMod.CheckForUpdates(ImportedModsItem ImportedModInfo, String feedBackMode) in C:\Users\moham\source\repos\Avlonia\mythosApp\mythos\Features\Mod\CheckForUpdates.cs:line 44]```
> ```
thanks for poitnitng out the movePack bug that bug has just been craeted by me in the last update when i was redoing the movePack funcaton.

**Comment by MohammedGamer85** [comment]
Fixed in 1.3
