### ISSUE TITLE
Links ignore colons leading to them being unable to open the correct webpage

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#83]
If a mod has a link to GitHub or Discord that contains a `:`, as in for `https://`, then the colon is ignored when clicking and opening the link, sending users to the wrong page (like `https//discord.gg` or `https//gihub.com`)

**Comment by Mohammed85-dev** [comment]
![image](https://github.com/MohammedGamer85/Mythtic/assets/100155245/ef1169fe-3563-4b8f-be86-7a91fe61cbdb)
i might have found out why let me fix that real quick

**Comment by Mohammed85-dev** [comment]
Fixed it by adding this instead
![image](https://github.com/MohammedGamer85/Mythtic/assets/100155245/315235b0-f51b-46c3-bcd9-8fd340c7166b)
